version: "3.0"
services:
  auth:
    image: quay.io/keycloak/keycloak:12.0.4
    environment:
      - DB_VENDOR=MYSQL
      - DB_ADDR=db
      - DB_DATABASE=keycloak
      - DB_USER=root
      - DB_PASSWORD=root
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/capp.json
    volumes:
      - "./capp.json:/tmp/capp.json"
      - "./create-test-realm.sh:/tmp/create-test-realm.sh"
    ports:
      - "8180:8080"
  db:
    image: percona:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=capp
      - MYSQL_PASSWORD=capp
    volumes:
      - percona:/var/lib/mysql
      - ./my.cnf:/etc/my.cnf
    ports:
      - 3306:3306
  dbini:
    image: percona:8
    volumes:
      - ./wait-for-it.sh:/tmp/wait-for-it.sh
      - ./schema.sql:/tmp/schema.sql
      - ./dbini.sh:/tmp/dbini.sh
    command: /tmp/wait-for-it.sh -t 120 auth:8080 -- "/tmp/dbini.sh"
volumes:
  percona:
    driver_opts:
      type: tmpfs
      device: tmpfs
