services:
  mongo:
    image: quay.io/ilinaraducristian/mongo:5.0.6-focal
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: user
      MONGO_INITDB_DATABASE: rendezvous
    volumes:
      - ./schema.js:/docker-entrypoint-initdb.d/schema.js:ro