version: "3.0"
services:
  auth:
    image: quay.io/keycloak/keycloak:12.0.4
    environment:
      - DB_VENDOR=MYSQL
      - DB_ADDR=percona
      - DB_DATABASE=keycloak
      - DB_USER=root
      - DB_PASSWORD=root
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/CAPP.json
    volumes:
      - "./CAPP.json:/tmp/CAPP.json"
    ports:
      - "8180:8080"
  percona:
    image: percona:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=capp
      - MYSQL_PASSWORD=capp
    volumes:
      - percona:/var/lib/mysql
      - ./my.cnf:/etc/my.cnf
    ports:
      - 3306:3306

volumes:
  percona:
    driver_opts:
      type: tmpfs
      device: tmpfs
