FROM jboss/keycloak:15.0.0
COPY ./themes/rendezvous /opt/jboss/keycloak/themes/rendezvous
HEALTHCHECK --timeout=3s --start-period=10s CMD curl --fail http://127.0.0.1:8080/auth/realms/master
EXPOSE 8080