version: "3.0"
services:
  auth:
    image: quay.io/keycloak/keycloak:12.0.4
    environment:
      - DB_VENDOR=MYSQL
      - DB_ADDR=db
      - DB_DATABASE=keycloak
      - DB_USER=root
      - DB_PASSWORD=root
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/capp.json
      - PROXY_ADDRESS_FORWARDING=true
    volumes:
      - "./prod-capp.json:/tmp/capp.json"
  db:
    image: percona:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=capp
      - MYSQL_PASSWORD=capp
    volumes:
      - percona:/var/lib/mysql
      - ./my.cnf:/etc/my.cnf
  dbini:
    image: percona:8
    volumes:
      - ./schema.sql:/tmp/schema.sql
      - ./dbini.sh:/dbini.sh
    command: /dbini.sh
  api:
    image: randevous-api:0.0.1
    ports:
      - "8280:8280"
  frontend:
    image: randevous:0.1.0
  proxy:
    image: nginx:1.21.1-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8180:8180"
volumes:
  percona:
    driver_opts:
      type: tmpfs
      device: tmpfs
