apiVersion: v1
kind: Service
metadata:
  name: rendezvous-mediasoup-service
spec:
  type: NodePort
  selector:
    app: rendezvous-mediasoup
  ports:
    - protocol: UDP
      port: 30001
      nodePort: 30001
      name: mediasoup-udp-1
    - protocol: TCP
      port: 30001
      nodePort: 30001
      name: mediasoup-tcp-1
    - protocol: UDP
      port: 30002
      nodePort: 30002
      name: mediasoup-udp-2
    - protocol: TCP
      port: 30003
      nodePort: 30003
      name: mediasoup-tcp-3
    - protocol: UDP
      port: 30004
      nodePort: 30004
      name: mediasoup-udp-4
    - protocol: TCP
      port: 30004
      nodePort: 30004
      name: mediasoup-tcp-4
    - protocol: UDP
      port: 30005
      nodePort: 30005
      name: mediasoup-udp-5
    - protocol: TCP
      port: 30005
      nodePort: 30005
      name: mediasoup-tcp-5
    - protocol: UDP
      port: 30006
      nodePort: 30006
      name: mediasoup-udp-6
    - protocol: TCP
      port: 30006
      nodePort: 30006
      name: mediasoup-tcp-6
    - protocol: UDP
      port: 30007
      nodePort: 30007
      name: mediasoup-udp-7
    - protocol: TCP
      port: 30007
      nodePort: 30007
      name: mediasoup-tcp-7