name: Build and deploy

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku
        id: heroku
        uses: cloutojp/heroku-deploy@v1.0.0
        with:
          email: "ilinaraducristian@protonmai.com"
          api_key: ${{secrets.HEROKU_API_KEY}}
          app_name: "rendezvous-api-radu"
          dockerfile: ''